name: LuaLink-Example
version: "1.0.0"
authors:
  - Element4521
main: xyz.galaxyy.lualink.addons.example.LuaLinkExampleAddon
description: A LuaLink addon example
api-version: "1.20"
dependencies:
  - name: LuaLink
    required: true
    bootstrap: false